# Cilium Ingress Controller Deployment 예제
# test용 nginx 배포
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    app: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
# test용 service 배포
apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  type: ClusterIP
  selector:
    app: test1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
# test용 ingress 배포
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
spec:
  ingressClassName: cilium
  rules:
  - host: test.cl.seungdobae.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test1
            port:
              number: 80